# Generated by Django 6.0.7 on 2026-07-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código de recuperación'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_code_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiración del código'),
        ),
    ]
