# Generated by Django 6.0.7 on 2026-07-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_reset_code_customuser_reset_code_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código de verificación'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_code_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiración del código de verificación'),
        ),
    ]
