# Generated by Django 6.0.7 on 2026-07-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('dark', 'Oscuro'), ('light', 'Claro')], default='dark', max_length=5, verbose_name='Tema'),
        ),
    ]
