# Generated by Django 6.0.7 on 2026-07-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('link', models.URLField(blank=True, verbose_name='Enlace (opcional)')),
                ('bg_color', models.CharField(blank=True, help_text='Ej: #ff0000', max_length=7, verbose_name='Color de fondo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Barra de oferta',
                'verbose_name_plural': 'Barras de ofertas',
            },
        ),
        migrations.DeleteModel(
            name='PromoBanner',
        ),
    ]
