# Generated by Django 6.0.7 on 2026-07-23 05:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(help_text='Clase de Bootstrap Icons (ej: bi-pc-display)', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(help_text='Ej: #003791 para PS5', max_length=7, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='developer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Desarrollador'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Descuento %'),
        ),
        migrations.AddField(
            model_name='product',
            name='format',
            field=models.CharField(choices=[('DIGITAL', 'Clave Digital'), ('PHYSICAL', 'Físico')], default='DIGITAL', max_length=10, verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_release',
            field=models.BooleanField(default=False, verbose_name='Nuevo lanzamiento'),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, verbose_name='Editor'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Valoración'),
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de lanzamiento'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='URL de video (tráiler)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Portada'),
        ),
        migrations.AddField(
            model_name='product',
            name='genres',
            field=models.ManyToManyField(to='dashboard.genre', verbose_name='Géneros'),
        ),
        migrations.AddField(
            model_name='product',
            name='platforms',
            field=models.ManyToManyField(to='dashboard.platform', verbose_name='Plataformas'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Imagen')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Principal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen del producto',
                'verbose_name_plural': 'Imágenes del producto',
            },
        ),
        migrations.CreateModel(
            name='SystemRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MINIMUM', 'Mínimos'), ('RECOMMENDED', 'Recomendados')], max_length=11, verbose_name='Tipo')),
                ('os', models.CharField(max_length=100, verbose_name='Sistema operativo')),
                ('cpu', models.CharField(max_length=200, verbose_name='Procesador')),
                ('ram', models.CharField(max_length=50, verbose_name='Memoria RAM')),
                ('gpu', models.CharField(max_length=200, verbose_name='Tarjeta gráfica')),
                ('storage', models.CharField(max_length=50, verbose_name='Almacenamiento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='dashboard.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Requisito del sistema',
                'verbose_name_plural': 'Requisitos del sistema',
            },
        ),
    ]
