# Generated by Django 6.0.7 on 2026-07-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_genre_platform_product_developer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Imagen de fondo para el hero del inicio (1920x1080 recomendado)', upload_to='hero/', verbose_name='Imagen de fondo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Hero de inicio',
                'verbose_name_plural': 'Hero de inicio',
            },
        ),
    ]
